1	tabs-2	Chart 1	Business Process	Business Process Strategic Importance\
	الأهمية الاستراتيجية طريقة العمل	bar1	tabs-2chartContainer1	bar	Count	[2,1,2,2,1]	[]	Strategic Importance\
	Business Process	["Very High","High","Medium","Low","Very Low"]	Element	Strategic Importance\
	admin	EAXee	1
3	tabs-2	Chart 2	Business Process	Business Process Strategic Importance	الأهمية الاستراتيجية طريقة العمل	bar1	tabs-2chartContainer2	bar	null	[5,4,3,5,1,2,3,2]	[{"y":5,"label":{"borderColor":"#FFFFFF","style":{"color":"#000000"},"position":"left","offsetY":5.5,"offsetX":-5,"text":"Very High"}},{"y":4,"label":{"borderColor":"#FFFFFF","style":{"color":"#000000"},"position":"left","offsetY":5.5,"offsetX":-5,"text":"High"}},{"y":3,"label":{"borderColor":"#FFFFFF","style":{"color":"#000000"},"position":"left","offsetY":5.5,"offsetX":-5,"text":"Medium"}},{"y":5,"label":{"borderColor":"#FFFFFF","style":{"color":"#000000"},"position":"left","offsetY":5.5,"offsetX":-5,"text":"Very High"}},{"y":1,"label":{"borderColor":"#FFFFFF","style":{"color":"#000000"},"position":"left","offsetY":5.5,"offsetX":-5,"text":"Very Low"}},{"y":2,"label":{"borderColor":"#FFFFFF","style":{"color":"#000000"},"position":"left","offsetY":5.5,"offsetX":-5,"text":"Low"}},{"y":3,"label":{"borderColor":"#FFFFFF","style":{"color":"#000000"},"position":"left","offsetY":5.5,"offsetX":-5,"text":"Medium"}},{"y":2,"label":{"borderColor":"#FFFFFF","style":{"color":"#000000"},"position":"left","offsetY":5.5,"offsetX":-5,"text":"Low"}}]	Business Process	Strategic Importance	["إعداد مشروع","إعداد ميثاق مشروع","طرح مشروع","إعداد خطة شاملة لمشروع","متابعة تنفيذ مشروع","إدارة مخرج مشروع","إدارة عوائق ومراقبة مخاطر مشروع","إدارة طلب تغيير"]	Element	Strategic Importance	admin	EAXee	1
4	tabs-2	Chart 3	Business Process	Business Process Maturity	نضج طريقة العمل	bar1	tabs-2chartContainer3	clusteredBar	Count	[{"name":"Initial","data":[0,1]},{"name":"Optimized","data":[1,1]},{"name":"Managed","data":[1,1]},{"name":"Adhoc","data":[1,1]},{"name":"Defined","data":[2,1]}]	null	Business Process Characteristics	null	["Current Maturity","Target Maturity"]	Element	["Current Maturity","Target Maturity"]	admin	EAXee	1
5	tabs-2	Chart 4	Business Application	null	null	bar1	tabs-2chartContainer4	pie	Distribution	[1000,5345435,1233,223333]	["Business_Application_XOWYup10","Business_Application_8rCcJG11","Business_Application_fle2qz12","Business_Application_J89frl13"]	Short Name	null	[]	Attribute	Functional Adequacy\
	admin	EAXee	1
6	tabs-2	Chart 5	Business Application	Business Application Criticality	الحرجة تطبيقات الأعمال	bar1	tabs-2chartContainer5	bar	Average	[{"name":"Optimized","data":[0,0,5,6]},{"name":"Managed","data":[0,4,0,0]},{"name":"Functional","data":[3,0,0,0]},{"name":"Challenged","data":[0,0,0,0]},{"name":"Initial","data":[0,0,0,0]},{"name":"None","data":[0,0,0,0]}]	null	Business Application	Average	["Business_Application_XOWYup10","Business_Application_8rCcJG11","Business_Application_fle2qz12","Business_Application_J89frl13"]	Attribute	["Functional Adequacy","Speed to Market"]	admin	EAXee	1
8	tabs-2	Chart 6	Business Application	Business Application	Business Application	bar1	tabs-2chartContainer6	clusteredBar	null	[{"name":"Functional Adequacy","data":["0.019","0.012","0.012","0.010"]},{"name":"Speed to Market","data":["0.044","0.034","0.039","0.020"]}]	null	null	Millions	["Business_Application_XOWYup10","Business_Application_8rCcJG11","Business_Application_fle2qz12","Business_Application_J89frl13"]	null	["Functional Adequacy","Speed to Market"]	admin	EAXee	1
